// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jieiqtgswrpvrswqamfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppZWlxdGdzd3JwdnJzd3FhbWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5OTk0NzIsImV4cCI6MjA2MTU3NTQ3Mn0.smvBT3H7_jou7x1RR07z65qBosz7qe3C7CzEx7oUW9A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);