// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icxwijpltzixfwlybufx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljeHdpanBsdHppeGZ3bHlidWZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5ODE1NjMsImV4cCI6MjA2MTU1NzU2M30.2vZwNRSb6mWklyRb_klC9jlidxfjikgCPtoJoKrvnZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);